//@api=http://127.0.0.1:3000/tasks
//@api=http://159.89.91.39:3000/tasks
//@api=http://127.0.0.1:4000/colaboradores

@api = https://nicolas-security.herokuapp.com/colaboradores


GET {{api}} HTTP/1.1

###
 
GET {{api}}/5 HTTP/1.1

###
GET {{api}}/count HTTP/1.1

###
POST {{api}}
Content-Type: application/json

{
    "nombre": "Franela",
    "telefono": 597777777
}

###
DELETE {{api}}/19

###

PUT {{api}}/10
Content-Type: application/json

{
    "nombre": "Beto a Saber",
    "telefono": 56977041571
}

