//@api=http://127.0.0.1:3000/tasks
//@api=http://159.89.91.39:3000/tasks
@api=http://127.0.0.1:4000/locales

//@api = https://nicolas-security.herokuapp.com/locales


GET {{api}} HTTP/1.1

###

@apiimagenes = http://127.0.0.1:4000/imagenes



GET {{apiimagenes}} HTTP/1.1

###
 
GET {{api}}/1 HTTP/1.1

###
GET {{api}}/count HTTP/1.1

###
POST {{api}}
Content-Type: application/json

{
    "local": "Botillería",
    "encargado": "Baltazar Contreras",
    "telefono": 56945078522,
    "ubicacion": "Esquina Sur",
    "estado":"abierto"
}

###
DELETE {{api}}/55

###

PUT {{api}}/55
Content-Type: application/json

{
     "local": "Botillería B",
    "encargado": "Baltazar",
    "telefono": 56962506125,
    "ubicacion": "Esquina Sur",
    "estado":"abierto"
}

